language: php

git:
    depth: 3

env:
    global:
        - APPLICATION_ENV=devtest
        - APPLICATION_STORE=EIN
        - PROJECT=spryker-click-and-collect
        - VALIDATION=1
        - secure: "d7g/fmV7jG6DoJt9LiLK3yMy96FwO/kfecTEGWoyJU5Q8hXZBeGt2pfqUTOD9vwa5j1zV8JCYXVP82Qefz+wDTYCoj92S16d4/5TVQetHAV4ZA2T9yUcbM7dH9KCVDhlpS0lvRflcc3aMIhyz1JUMlIZJq/hCyXEsKxp6lNPl8L7CpQEViw7ecrXoRPSD5mw1aIyquDrB1sOysZ+lQef0AjzXLBuhEyobW4MZrdhj2UbRsXKP31YDI8MdMr8OR0LKsMH1gW+NrpBYqAoRROFjUvmSfviGhaYtL2O9WpIbFtNyF/IPItJtBcdWdEqQrXOIwRzQshln/hzXV5WVbHyKnLTGG+YrPa6M52vBpFmuSn/vfw/w/fwObmC4kOdR/6+h8F6YdX4YXUj5SVjh8Rf4NKvhcIG8MklOL6mi+hR/dc7Hq3hYzJipcQxb6UlbUJQlGiCKGimnZbyKMPqN5hJ8+PuGu1SLZajx0mqw/44tR47ay38q6NhTjMRil5rb+oHjTKsDNW3stE3v6xYnHH8ORCcI+jUrW7Rj7wjcWwS9zxT7GoqCm1gbTpgTpnnJs6DnkuNPAUr3Rmab8p/fNHRD7AqOIRaxg3vLIXW8lyigs6LN9pVajtEr0H8TFdc3+nRVByQpcpc1398JiuuuV+yhx9dZmKRtLWVzXJvlB5iPeY="

matrix:
    fast_finish: true
    include:
        - php: "7.3"
          dist: trusty
addons:
    mariadb: "10.4"

    apt:
        packages:
            - graphviz

    hosts:
        - backoffice.globus.test
        - www.globus.test

cache:
    directories:
        - $HOME/.composer/cache
        - /home/travis/.rvm/gems # Mailcatcher is a ruby gem, takes 5 minutes to install.

services:
    - redis
    - rabbitmq
    - mysql

sudo: required

before_install:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - phpenv config-rm xdebug.ini

install:
    - chmod -R a+x config/Shared/ci/travis/
    - composer self-update --1
    - composer global require hirak/prestissimo
    - composer install --optimize-autoloader --no-interaction
    - config/Shared/ci/travis/install_elasticsearch.sh
    - config/Shared/ci/travis/install_mailcatcher.sh

before_script:
    - nvm install 8

    - mkdir -p shared/data/common/jenkins
    - mkdir -p shared/data/common/jenkins/jobs
    - mkdir -p data/EIN/cache/Yves/twig -m 0777
    - mkdir -p data/EIN/cache/Zed/twig -m 0777
    - mkdir -p data/EIN/logs -m 0777
    - mkdir -p src/Orm/Propel/EIN/Schema -m 0777
    - chmod -R 777 data/
    - chmod -R 660 config/Zed/dev_only_private.key
    - chmod -R 660 config/Zed/dev_only_public.key

    - cat config/Shared/ci/travis/mysql_ci.config >> config/Shared/ci/travis/config_ci.php

    - cp config/Shared/ci/travis/config_ci.php config/Shared/config_local.php

    - vendor/bin/install EIN -r testing -x frontend -v

    - vendor/bin/console transfer:generate
    - vendor/bin/console propel:install
    - vendor/bin/codecept build --ansi
    - vendor/bin/console transfer:databuilder:generate
    - vendor/bin/console setup:search
    - vendor/bin/console frontend:project:install-dependencies
    - vendor/bin/console frontend:yves:install-dependencies

script:
#    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/StoreApp/Zed -l 4 --debug
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/Pyz/Zed -l 3 --debug
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/Pyz/Client -l 4 -vvv
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/Pyz/Glue -l 4 -vvv
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/Pyz/Shared -l 4 -vvv
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/Pyz/Service -l 4 -vvv
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/Pyz/Yves -l 4 -vvv
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/SprykerConfig -l 4 -vvv
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/StoreApp/Shared -l 4 -vvv
    - php -d memory_limit=5376M vendor/bin/phpstan analyze -c phpstan.neon src/StoreApp/Yves -l 4 -vvv
#    - php -d memory_limit=-1 vendor/bin/phpstan analyze -c phpstan.neon src/ -l 4
#    - vendor/bin/phpstan analyze -c phpstan.neon src/ -l 4

    - vendor/bin/console propel:schema:validate-xml-names
    - vendor/bin/console transfer:validate
    - vendor/bin/console code:sniff:style src

    - timeout 45m bash -c "vendor/bin/phantomjs --webdriver=4444 --disk-cache=true --load-images=false" &
    - vendor/bin/codecept run -x Presentation

#    - node ./frontend/libs/stylelint
#    - node ./frontend/libs/tslint stylish

notifications:
    email: false
